-- MySQL Script generated by MySQL Workbench
-- jeu. 10 nov. 2022 09:35:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Datasound
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Datasound
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Datasound` ;
USE `Datasound` ;

-- -----------------------------------------------------
-- Table `Datasound`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Datasound`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `email` VARCHAR(75) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `isAdmin` TINYINT NOT NULL,
  `isVerified` TINYINT NOT NULL,
  `isBan` TINYINT NOT NULL,
  `ppUser` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Datasound`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Datasound`.`comments` (
  `id_comments` INT NOT NULL AUTO_INCREMENT,
  `commentary` VARCHAR(255) NOT NULL,
  `id_user` INT NOT NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id_comments`),
  UNIQUE INDEX `id_comments_UNIQUE` (`id_comments` ASC) VISIBLE,
  CONSTRAINT `fk_Comments_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `Datasound`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Datasound`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Datasound`.`message` (
  `id_message` INT NOT NULL,
  `sujet` TEXT NULL,
  `message` VARCHAR(450) NULL,
  `id_user` INT NULL,
  PRIMARY KEY (`id_message`),
  INDEX `fk_Msg_Admin_1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_Message`
    FOREIGN KEY (`id_user`)
    REFERENCES `Datasound`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
